export const data = [
  {
    name: "Raghubendra Raja",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "212643131@trucard",
  },
  {
    name: "Abhinab Loyal",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Pending",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Pay and Use",
    tpa: "212643131@trucard",
  },
  {
    name: "Raghu Raju",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "212643131@trucard",
  },
  {
    name: "Raghubendra Raja",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "212643131@trucard",
  },
  {
    name: "Ashis Raja",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "212643131@trucard",
  },
  {
    name: "Raghubendra Raja",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "212643131@trucard",
  },
  {
    name: "Raghubendra Raja",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "212643131@trucard",
  },
  {
    name: "Raju Raja",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Pending",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "212643131@trucard",
  },
  {
    name: "Raghubendra Raja",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "212643131@trucard",
  },
  {
    name: "Raghubendra Raja",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "212643131@trucard",
  },
  {
    name: "Raghubendra Raja",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "212643131@trucard",
  },
  {
    name: "Raghubendra Raja",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "212643131@trucard",
  },
];
